#ifndef KERNEL_H
#define KERNEL_H

#include "askr-types.h"

#define NULL 0

#define VGA_ADDRESS 0xB8000
#define BUFFERSIZE 2200

#define VGA_WIDTH 80
#define VGA_HEIGHT 25

UINT16* VGA_BUFFER;

enum VGA_COLOR { BLACK, BLUE, GREEN, CYAN, RED, MAGENTA, BROWN, GREY, DARK_GREY, BRIGHT_BLUE, BRIGHT_GREEN, BRIGHT_CYAN, BRIGHT_RED, BRIGHT_MAGENTA, YELLOW, WHITE, };

#endif